package com.eternalfragment.bookofblocks.operators;

import com.eternalfragment.bookofblocks.Bookofblocks;
import com.eternalfragment.bookofblocks.config.Config;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.entity.player.PlayerInventory;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.server.network.ServerPlayerEntity;

public class invManager {

    public static int inv_PayItem(PlayerEntity player, int itemID, int amt){
        PlayerInventory pI = player.getInventory();
        Item item = Registries.ITEM.get(itemID).asItem();
        item.getDefaultStack();
        int numInInventory=pI.count(Registries.ITEM.get(itemID));
        System.out.println("----INV REMOVAL----");
        System.out.println("itemID: "+itemID+"  amt: "+amt+"  inInv: "+numInInventory);
        if (numInInventory>=amt) {
            int numRemoved=0;
            boolean keepSearch=true;
            int invSize = pI.size();
            ItemStack findStack = Registries.ITEM.get(itemID).getDefaultStack();
            while (keepSearch){
                if (numRemoved<amt){
                    int amtLeftRemove=amt-numRemoved;

                    int itemIndex = pI.indexOf(findStack);
                    System.out.println("amtLRemove: "+amtLeftRemove+" | Foundat index: "+itemIndex+" stackdata: "+findStack.toString());
                    if (itemIndex >=0){
                    int numInStack = pI.getStack(itemIndex).getCount();
                    int removeAmt=Math.min(numInStack,amtLeftRemove);
                    pI.removeStack(itemIndex,removeAmt);
                    numRemoved=numRemoved+removeAmt;
                    }else{
                        keepSearch=false;
                    }
                }else{
                    keepSearch=false;
                }
            }
            return numRemoved;
        }else {
            Bookofblocks.mylogger.atError().log("[PayItem]... ERROR IN TRANSMISSION -- invalid amts");
            return 0;
        }
    }
    public static void inv_giveItem(ServerPlayerEntity player, int itemID, boolean fullStack){
        int amt=1;
        String itemName=String.valueOf(Registries.ITEM.get(itemID).asItem());
        Object[] iConfig = Config.configMap.get(itemName);
        if (fullStack) {amt=(int)iConfig[3];}
            for (int i=0; i<amt; i++){
                ItemStack thisItem = new ItemStack(Registries.ITEM.get(itemID).asItem());
               /*
               TODO: When Alternate config options are set, utilize NBT tags for items generated by MJM as an OPTION
               NbtCompound nbt;
                if (thisItem.hasNbt()){
                    nbt=thisItem.getNbt();
                }else{
                    nbt = new NbtCompound();
                }
                nbt.getBoolean("bob_generated");
                nbt.putBoolean("bob_generated",true);
                thisItem.setNbt(nbt);
                String CleanItemName = itemName.replaceAll("_", " ").toLowerCase();
                CleanItemName = WordUtils.capitalizeFully(CleanItemName);
                thisItem.setCustomName(Text.of("*"+CleanItemName));*/
            if(!player.getInventory().insertStack(thisItem)){
                //Inventory full?
                break;
            }
        }
    }
    public static int inv_clearItem(ServerPlayerEntity player,int itemID){
        ItemStack findStack = Registries.ITEM.get(itemID).getDefaultStack();
        boolean keepSearch = true;
        int numRemoved=0;
        int numInInventory=player.getInventory().count(Registries.ITEM.get(itemID));
        while (keepSearch){
            if (numRemoved<numInInventory){
                int amtLeftRemove=numInInventory-numRemoved;
                int itemIndex = player.getInventory().indexOf(findStack);
                if (itemIndex >=0){
                    int numInStack = player.getInventory().getStack(itemIndex).getCount();
                    int removeAmt=Math.min(numInStack,amtLeftRemove);
                    player.getInventory().removeStack(itemIndex,removeAmt);
                    numRemoved=numRemoved+removeAmt;
                }else{
                    keepSearch=false;
                }
            }else{
                keepSearch=false;
            }
        }
        return numRemoved;

    }

}
